branches:
    only:
    - master

language: python

env:
    global:
        secure: oHlWkMZ80dzVEryTuknWC/NHS7fBJMxjEgAfn7iNgtST4KA6WTjLXMiO1fiwXsl95y7rA/pVk7SV7wEaMZ4FUGMRBmkhck2m20nuWNvbJdZVns/ux4/QNAwUxLbcf3UbzHaA9y8W9ABAqooTYfp+GzZzWzE3TviZjEn2AoVPdzGEEDYltcL5rEaTZ1bzXsxM1v/kM5Ijv7MdR3v8zO+DbNC5vtmK5v+wg8S2U1+XvJrB2zYnv2GkLb/467zupio1P1+8q40tgK014tkhPu/krj6C961cTLlkciL+23VtwgBLSwPRbr4+29MMNNDCBG7Gov3saMU9Bzlfpc278k5Bt3wqiEAnHehZhbxosgs917RlJThwHArZ9xpzaJYI37g8Pl1GyllcaOHP3DwwtEsFc6l9UWFMkMvX4BJwRDsRxUK0L3Z33auCX1gs3S4cDokJMjQ1vSJ1IZmjnpIG0R2lpre3MTaSa0HZ44fFddeONZrIsT4rfppP9GRk+JQ7hZyXVJULiRJc8nT0aNh2/06UpzvdgG583p2VWGqlPcYPsR/seSmeTGHqgndLjGgNWKU2230lZAE/zWjTSvMyDn2zxarWgg/cpdGrjx5TogopO+t8W+ijSAuFB1ehSeSuFEGBBIgJBoWMISbVSENIRP8ApEsaxEg27Xi5//ykmXMwQJw=
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=development
        - PIP_DEPENDENCIES='Markdown fabric git+https://github.com/jakevdp/JSAnimation.git'
        - CONDA_DEPENDENCIES='ipython jupyter pelican'

python:
    - 3.5

install:
    # use astropy ci-helpers
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

script:
    - make html

notifications:
    email:
        on_success: always
        on_failure: always

before_install:
    - git submodule update --init --recursive

after_success: bash deploy.sh
